### ISSUE TITLE
Demo doesn't run

### ISSUE THREAD

**Issue by alexleventer** [segmentio/sherlock#23]
Getting the following error when I try to run the demo:

```
phantom stdout: NETWORK_ERR: XMLHttpRequest Exception 101: A network error occurred in synchronous requests.

phantom stdout:   phantomjs://code/shim.js:1815 in send
  phantomjs://code/shim.js:1815 in _start
  phantomjs://code/shim.js:1842
```

Do you guys have a new repo you're using for script detection?

**Comment by dominicbarnes** [comment]
Ah, I haven't really looked at this codebase in over a year. It could probably use a refresher, and an update to the latest version of nightmare. (it uses Electron, which is much more stable than PhantomJS) Plus, not sure how well this works on newer versions of node. (ie: 4+)

**Comment by dominicbarnes** [comment]
I reproduced this problem, and I have a workaround. Apparently, our version of Nightmare doesn't work well with PhantomJS v2.x.

If you install PhantomJS v1 to your system, it works again. (I did this via `npm -g install phantomjs@1`) We don't really use this library in our app atm, but I'll see if I can spare some time to bring this up-to-date.

**Comment by alexleventer** [comment]
Cool thanks @dominicbarnes - I'm working on updating this w/ the new version of Phantom, I'll send over a PR when I'm done.
